title: YASSINE BEN EL HAJ # your name (or website title) here
logo: "/images/FB_IMG_1723812355727.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  Welcome to my portfolio! I am a Data Analyst with over six years of experience, specializing in supply chain optimization and risk management. My expertise in data analysis and dashboard solutions has significantly reduced stockouts and excess inventory.  
  <br><br> 
  With a background in Actuarial Science and Risk Management, I excel in Python and data analytics tools to create impactful visualizations and predictive models. I transform data into actionable insights to improve processes. Browse my projects to see how I solve real-world problems with analytics.  
  <a href="https://www.linkedin.com/in/yassben/">View My LinkedIn Profile</a> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-X8YJC9BVMQ # your Google Analytics tracking ID here
