title: YASSINE BEN EL HAJ # your name (or website title) here
logo: "/images/FB_IMG_1723812355727.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
Welcome to my portfolio! I am a Data Analyst with over six years of experience in supply chain optimization and risk management. Leveraging my background in Actuarial Science, I excel in Python and data analytics tools to create visualizations and predictive models. 
<br><br> 
My work focuses on transforming data into actionable insights to enhance processes. Explore my projects to see how I tackle real-world analytics challenges. 
  <a href="https://www.linkedin.com/in/yassben/">View My LinkedIn Profile</a> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-X8YJC9BVMQ # your Google Analytics tracking ID here
